language: c++
jobs:
  include:
    - name: Linux (Ubuntu Bionic)
      os: linux
      dist: bionic
      # virt: lxd
    - name: Linux (Ubuntu Xenial)
      os: linux
      dist: xenial
      # virt: lxd
    - name: MacOSX
      os: osx
#    - name: Linux (Ubuntu Bionic on arm64)
#      os: linux
#      virt: lxd
#      arch: arm64
#      dist: bionic
git:
  depth: 1
script:
  - make -j4 CXXDEBUGFLAGS= CXXOPTFLAGS=-O0
