language: c++
dist: 
  - focal
  - bionic
  - xenial
os:
  - linux
  - osx
virt: lxd
#sudo: require
#addons:
#  apt:
#    packages:
#      - doxygen
#      - swig
compiler:
  - g++
git:
  depth: 1
script:
  - make -j4 CXXDEBUGFLAGS= CXXOPTFLAGS=-O0
